/* Shared data: services, time slots, consent texts */
export const serviceCategories = [
  {
    id: 'infusion', title: 'IV & Infusion Services', icon: '\u2726',
    services: [
      { id: 1, title: 'Signature Soulution', desc: 'Customized IV infusions delivered in the comfort of your home or office, tailored to your unique wellness needs.', tags: ['Hydration', 'Vitamin Therapy', 'NAD+', 'Immunity Boost'] },
      { id: 20, title: 'Hangover Soulution', desc: 'IV fluids, electrolytes, anti-nausea, B-vitamins, and antioxidants for rapid hangover recovery.', tags: ['Hangover', 'Rehydration', 'Anti-Nausea', 'Electrolytes'] },
      { id: 21, title: 'Migraine Soulution', desc: 'Magnesium, anti-inflammatory agents, hydration, and targeted vitamins for migraine relief.', tags: ['Migraine', 'Headache', 'Magnesium', 'Pain Relief'] },
      { id: 22, title: 'Hydration Soulution', desc: 'Rapid IV fluid and electrolyte replenishment for illness, exercise, travel, or heat exposure.', tags: ['Dehydration', 'Electrolytes', 'Fluid Replacement', 'Rapid Recovery'] },
      { id: 23, title: 'Immunity Soulution', desc: 'High-dose vitamin C, zinc, and glutathione IV to boost immune defense.', tags: ['Immune Support', 'Vitamin C', 'Zinc', 'Glutathione'] },
      { id: 24, title: 'Vitamin Soulution', desc: "Myers' Cocktail, B-complex, vitamin D, and custom vitamin/mineral IV blends.", tags: ["Myers' Cocktail", 'B-Complex', 'Vitamin D', 'Nutrient Optimization'] },
      { id: 25, title: 'Mitochondrial Health Soulution', desc: 'NAD+ precursor therapy for cellular energy, healthy aging, and metabolic support.', tags: ['Niagen', 'NR', 'NAD+ Precursor', 'Cellular Health'] },
      { id: 26, title: 'NAD+ Soulution', desc: 'IV NAD+ for cellular energy, brain health, mental clarity, and anti-aging.', tags: ['NAD+', 'Anti-Aging', 'Brain Health', 'Cellular Energy'] },
      { id: 27, title: 'Jet Lag Soulution', desc: 'Hydration, B-vitamins, magnesium, and adaptogens to combat jet lag.', tags: ['Jet Lag', 'Travel Recovery', 'Energy', 'Rehydration'] },
      { id: 28, title: 'Digestive Soulution', desc: 'Anti-inflammatory nutrients, glutamine, zinc, and B-vitamins for GI support.', tags: ['Digestive Health', 'Gut Support', 'Glutamine', 'Anti-Inflammatory'] },
      { id: 41, title: 'Colonoscopy Hydration Soulution', desc: 'Pre/post-colonoscopy IV hydration at home. Maintain electrolytes during prep, restore fluids after.', tags: ['Colonoscopy Prep', 'Post-Procedure', 'Electrolytes', 'Bowel Prep Hydration'] },
      { id: 42, title: 'Custom Soulution', desc: 'Build your own IV drip tailored to your specific needs. Work with our clinician to select vitamins, minerals, amino acids, and add-ons for a fully personalized infusion.', tags: ['Custom', 'Personalized', 'Build Your Own', 'Tailored Therapy'] },
      { id: 3, title: 'Injection & Infusion Assistance Soulution', desc: 'Professional administration of prescribed injections and infusions with expert nursing care.', tags: ['B12 Injections', 'Medication Infusions', 'Subcutaneous', 'Intramuscular'] },
    ],
  },
  {
    id: 'homecare', title: 'In-Home & Post-Op Care', icon: '\u2756',
    services: [
      { id: 6, title: 'In-Home & In-Hospital Nursing', desc: 'Skilled nursing care provided at your bedside, whether at home or during a hospital stay.', tags: ['Bedside Care', 'Skilled Nursing', 'Monitoring', 'Recovery'] },
      { id: 7, title: 'Concierge Post-Op Care', desc: 'Dedicated post-surgical nursing care to ensure a smooth, comfortable recovery.', tags: ['Post-Surgery', 'Wound Care', 'Pain Management', 'Recovery'] },
      { id: 40, title: 'Nurse Escort Home After Anesthesia', desc: 'Licensed nurse escort home after anesthesia. Vital sign monitoring, symptom management, safe transport, discharge review.', tags: ['Anesthesia Escort', 'Safe Discharge', 'Post-Sedation', 'Transport'] },
      { id: 8, title: 'Nursing Advocate', desc: 'A dedicated nurse advocate to help navigate the healthcare system and ensure quality care.', tags: ['Patient Advocacy', 'Care Coordination', 'Healthcare Navigation'] },
    ],
  },
  {
    id: 'diagnostics', title: 'Diagnostics & Lab Services', icon: '\u2695',
    services: [
      { id: 50, title: 'At-Home Blood Draw & Phlebotomy', desc: 'Convenient in-home blood collection by a licensed nurse, with samples delivered to an accredited laboratory for processing.', tags: ['Phlebotomy', 'Venipuncture', 'In-Home Collection', 'Lab Ready'] },
      { id: 51, title: 'At-Home Lab Testing', desc: 'Bloodwork and diagnostic panels collected in the comfort of your home and sent to an accredited laboratory, from routine wellness panels to targeted screenings.', tags: ['Lab Panels', 'Wellness Screening', 'Diagnostics', 'Bloodwork'] },
      { id: 52, title: 'Lab Result Interpretation', desc: 'A Nurse Practitioner reviews and interprets your laboratory results and discusses findings and next steps with you.', tags: ['NP Review', 'Result Interpretation', 'Care Plan', 'Follow-Up'] },
      { id: 53, title: 'Respiratory Swabs', desc: 'In-home collection of respiratory specimens for testing such as COVID-19, influenza, RSV, and strep, with results reviewed by a clinician.', tags: ['COVID-19', 'Influenza', 'RSV', 'Strep'] },
      { id: 54, title: 'Urine Testing', desc: 'In-home urine specimen collection for urinalysis and related testing, processed by an accredited laboratory.', tags: ['Urinalysis', 'UTI Screening', 'Specimen Collection', 'Diagnostics'] },
    ],
  },
  {
    id: 'wellness', title: 'Wellness & Management', icon: '\u2727',
    services: [
      { id: 9, title: 'Weight Management', desc: 'Medically guided weight management with personalized nutrition and lifestyle counseling.', tags: ['Nutrition', 'Lifestyle', 'Metabolic Health', 'Coaching'] },
      { id: 4, title: 'Medication Education', desc: 'Comprehensive medication teaching and management to ensure safe, effective use of your prescriptions.', tags: ['Medication Review', 'Drug Interactions', 'Patient Education'] },
      { id: 10, title: 'Personalized Care Plans', desc: 'Comprehensive, individualized care plans developed by our nurse practitioners.', tags: ['Assessment', 'Care Planning', 'Wellness Goals', 'Follow-Up'] },
      { id: 55, title: 'Supplement Protocols', desc: 'Supplement and nutraceutical protocols tailored uniquely for you by our nursing team, based on your health goals, history, and lab results. Educational and wellness-focused; not intended to diagnose, treat, cure, or prevent any disease.', tags: ['Nutraceuticals', 'Personalized', 'Vitamins & Minerals', 'Wellness'] },
      { id: 5, title: 'Telehealth Services', desc: 'Virtual consultations with our nurse practitioners from the comfort of your home.', tags: ['Virtual Visit', 'Remote Monitoring', 'Follow-Up', 'Consultation'] },
    ],
  },
];

export const timeSlots = [
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM', '3:00 PM', '3:30 PM',
  '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM',
];

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   CONSENT TEXTS
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */

export const CONSENT_TREATMENT = `INFORMED CONSENT FOR TREATMENT - BT RPN PLLC & Kristina Castro, Nurse Practitioner in Family Health, PLLC, providing services under the licensed name Healing Soulutions
Effective Date: August 1, 2026

I voluntarily consent to healthcare services from BT RPN PLLC and Kristina Castro, Nurse Practitioner in Family Health, PLLC, which provide services under the licensed name Healing Soulutions (the "Practice"), including nursing assessments, IV hydration and vitamin/nutrient infusion therapy, injections and injection/infusion assistance, wound care, post-operative and post-anesthesia nursing care, nurse escort services, medication administration and medication education, health screenings, phlebotomy and specimen collection (including respiratory swabs and urine specimens), diagnostic laboratory testing and result interpretation, medically supervised weight management, telehealth consultations, personalized care planning, supplement and nutraceutical protocols, and related wellness services.

NATURE OF SERVICES: Mobile, concierge, in-home, and/or telehealth services provided by licensed Registered Nurses (RNs) and Nurse Practitioners (NPs) in accordance with New York Education Law Article 139. Services are provided in non-traditional settings including private residences, hotels, offices, and other locations designated by the patient. I understand that mobile and in-home healthcare delivery may present limitations not present in traditional clinical settings, including but not limited to access to emergency equipment, sterile environments, on-site laboratory services, and immediate physician backup.

RISKS AND COMPLICATIONS: I acknowledge that all medical procedures carry inherent risks. Risks associated with services provided include but are not limited to: pain, bruising, swelling, or infection at IV/injection sites; allergic or anaphylactic reactions to medications, vitamins, supplements, or other administered substances; hematoma, nerve injury, phlebitis, thrombophlebitis, or vascular injury; dizziness, nausea, vomiting, or fainting (vasovagal syncope); air embolism (rare but potentially serious); infiltration or extravasation of IV fluids; fluid overload or electrolyte imbalance; adverse drug reactions or interactions with current medications; cardiac arrhythmia (rare, associated with certain IV therapies); delayed healing or scarring at treatment sites; and unforeseen complications that may require emergency medical intervention. Benefits may include improved hydration, symptom relief, enhanced wellness, and recovery support. No specific outcomes or results are guaranteed.

MEDICATION, INJECTABLE & PRESCRIPTION THERAPIES: I understand that certain services involve the administration of prescription medications, vitamins, nutrients, and other injectable or infusible substances ordered by a Nurse Practitioner following clinical evaluation. Some medications may be used for FDA-approved indications, and some may be prescribed off-label where clinically appropriate and consistent with accepted standards of care. Certain preparations may be obtained from licensed compounding pharmacies operating under Sections 503A or 503B of the Federal Food, Drug, and Cosmetic Act; compounded medications are not reviewed by the FDA for safety and effectiveness as finished drug products. I understand that all medications carry risks of side effects, allergic reactions, and interactions, that a clinical evaluation is required before any medication is provided, and that no specific result is guaranteed.

TELEHEALTH SERVICES CONSENT (IF APPLICABLE): I consent to receive services via telehealth as provided under New York Public Health Law Article 29-G. I understand that: (a) telehealth uses electronic communications to enable a provider to evaluate, and where appropriate diagnose and treat, me remotely; (b) the same standards of care, privacy, and confidentiality that apply to in-person services apply to telehealth; (c) telehealth has potential limitations, including that the provider may be unable to perform a hands-on physical examination and that technical failures may interrupt or affect the quality of the visit; (d) certain conditions are not appropriate for telehealth and I may be directed to seek in-person or emergency care; (e) I have the right to refuse telehealth and to request in-person services where available, without affecting my right to future care; and (f) I am responsible for providing a private, secure environment for the visit. I understand that telehealth is not a substitute for emergency care, and in an emergency I will call 911.

ASSUMPTION OF RISK: I understand and voluntarily assume all risks associated with the services described herein, including risks that are known, unknown, anticipated, or unanticipated. I acknowledge that the practice of medicine and nursing is not an exact science and that no guarantees have been made to me regarding the outcome of any treatment or procedure.

LIMITATION OF LIABILITY: To the fullest extent permitted by applicable law, I agree that the Practice, its owners, officers, employees, contractors, agents, and affiliated clinicians (collectively, the Released Parties) shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to the services provided. The Released Parties' total aggregate liability for any direct damages shall not exceed the total fees paid by me for the specific service giving rise to the claim. This limitation applies regardless of the theory of liability, whether in contract, tort (including negligence), strict liability, or otherwise.

INDEMNIFICATION: I agree to indemnify, defend, and hold harmless the Released Parties from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or related to: (a) my failure to disclose material medical information including but not limited to pre-existing conditions, medications, allergies, substance use, or prior adverse reactions; (b) my failure to follow post-treatment instructions or recommendations provided by the clinician; (c) my use of services against medical advice or after being informed of contraindications; (d) any misrepresentation made by me in connection with the services; or (e) my violation of any term of this agreement.

RELEASE AND WAIVER: I, on behalf of myself, my heirs, executors, administrators, legal representatives, successors, and assigns, hereby release, waive, and forever discharge the Released Parties from any and all claims, demands, actions, causes of action, suits, damages, losses, and expenses of any kind or nature whatsoever, whether known or unknown, which I now have or may hereafter have, arising out of or in connection with the services provided, except to the extent caused by the gross negligence or willful misconduct of the Released Parties. I expressly waive any rights I may have under Section 1542 of the California Civil Code or any similar statute of any other jurisdiction which provides that a general release does not extend to claims not known at the time of executing the release.

NO GUARANTEE OF RESULTS: I acknowledge that no guarantees, warranties, or assurances have been made to me regarding the outcome, effectiveness, or results of any treatment, procedure, or service. The Practice expressly disclaims any implied warranties, including but not limited to implied warranties of merchantability and fitness for a particular purpose, to the fullest extent permitted by law.

PATIENT RESPONSIBILITY: I acknowledge my obligation to: (a) provide complete, accurate, and truthful medical history and health information; (b) inform the clinician of all current medications, supplements, and substances used; (c) disclose all known allergies and prior adverse reactions; (d) follow all pre-treatment and post-treatment instructions; (e) seek emergency medical care if I experience any severe or unexpected symptoms following treatment; (f) notify the Practice immediately of any adverse reactions or complications; and (g) attend all recommended follow-up appointments. I understand that failure to comply with these obligations may result in adverse outcomes for which the Practice shall not be held liable.

EMERGENCY AUTHORIZATION: In the event of a medical emergency arising during or after treatment, I authorize the Practice and its clinicians to initiate emergency protocols, contact emergency medical services (911), and share relevant medical information with emergency responders and healthcare facilities as necessary to protect my health and safety. I understand that any costs associated with emergency medical transport or treatment at an outside facility are my sole responsibility.

SCOPE OF PRACTICE & TEAM-BASED CARE: I understand that the Practice utilizes a team-based approach. Nurse Practitioners (NP): NPs are licensed to diagnose illness, prescribe medications, and initiate treatment plans under New York Education Law Section 6902. Registered Nurses (RN): RNs provide nursing care and execute medical regimens (such as IV infusions or injections) only under the specific order or standing order of a Nurse Practitioner or Physician. I understand that if my care is delivered by an RN, they are acting under the clinical direction of the Practice's NP. The RN does not independently diagnose medical conditions or prescribe treatments. Services provided are not a substitute for emergency medical care, primary care physician visits, or specialist consultations. The Practice does not assume the role of the patient's primary care provider.

DISPUTE RESOLUTION: Any dispute, claim, or controversy arising out of or relating to this agreement or the services provided shall first be submitted to good faith mediation. If mediation is unsuccessful, disputes shall be resolved through binding arbitration administered in accordance with the rules of the American Arbitration Association, with proceedings conducted in the State of New York. The prevailing party in any arbitration or legal proceeding shall be entitled to recover reasonable attorneys' fees and costs.

PRESERVATION OF CARE CLAIMS: Notwithstanding the Limitation of Liability, Release and Waiver, Indemnification, and Dispute Resolution sections above, nothing in this agreement limits, waives, or requires arbitration of any claim for personal injury or wrongful death arising from professional negligence in the delivery of clinical care. Such claims are preserved and governed by applicable New York law and the Practice's professional liability coverage.

ELECTRONIC SIGNATURE & RECORDS CONSENT: I consent to conduct this transaction and to sign this and related documents by electronic means. I agree that my electronic signature is the legal equivalent of my handwritten signature and is valid and binding under the federal Electronic Signatures in Global and National Commerce Act (E-SIGN Act, 15 U.S.C. Section 7001 et seq.) and the New York Electronic Signatures and Records Act (ESRA, State Technology Law Article 3). I confirm that I am able to access and retain documents provided in electronic form. I may request a paper copy of any signed document and may withdraw my consent to electronic delivery by contacting the Practice, without affecting the validity of any document already signed.

SEVERABILITY: If any provision of this consent is found to be invalid, illegal, or unenforceable, such finding shall not affect the validity of the remaining provisions, which shall continue in full force and effect.

VOLUNTARY CONSENT: This consent is given pursuant to NY PHL Section 2805-d. I have the right to refuse or withdraw consent at any time without penalty. Both entities maintain professional malpractice insurance. I have been given the opportunity to ask questions and all my questions have been answered to my satisfaction. I have read, or have had read to me, this entire document. I understand its contents and I freely and voluntarily consent to the services described herein.

ACKNOWLEDGMENT: By signing below, I certify that I am at least 18 years of age (or the legal guardian of the patient), that I have the legal capacity to enter into this agreement, that I have read and fully understand all terms and conditions set forth herein, and that I voluntarily consent to treatment and agree to all terms of this Informed Consent.`;

export const CONSENT_HIPAA = `NOTICE OF PRIVACY PRACTICES - BT RPN PLLC & Kristina Castro, Nurse Practitioner in Family Health, PLLC, providing services under the licensed name Healing Soulutions
Effective Date: August 1, 2026

This notice is required by the Health Insurance Portability and Accountability Act of 1996 (HIPAA), the Health Information Technology for Economic and Clinical Health Act (HITECH), 45 CFR Parts 160 and 164, and applicable New York State law to inform you of how your Protected Health Information (PHI) may be used and disclosed, and your rights regarding your PHI.

PERMITTED USES AND DISCLOSURES: Your PHI may be used and disclosed without your authorization for the following purposes: (a) Treatment — to provide, coordinate, and manage your healthcare and related services, including consultations between healthcare providers; (b) Payment — to obtain reimbursement for services, including billing, claims management, and collection activities; (c) Healthcare Operations — to support the business activities of the Practice including quality assessment, staff training, compliance, auditing, and business planning; (d) As Required by Law — when federal, state, or local law requires disclosure; (e) Public Health Activities — as required for public health surveillance, investigations, or interventions; (f) Business Associates — to entities that perform services on our behalf under a Business Associate Agreement that requires them to safeguard your PHI.

AUTHORIZATION REQUIRED: Written authorization is required before we may use or disclose your PHI for the following: psychotherapy notes; marketing purposes; sale of PHI; HIV-related information (NY PHL Article 27-F); substance abuse treatment records (42 CFR Part 2); mental health records (NY MHL Section 33.13); and genetic information (Genetic Information Nondiscrimination Act - GINA). You may revoke any authorization in writing at any time, except to the extent the Practice has already acted in reliance upon it.

YOUR RIGHTS: You have the following rights regarding your PHI: (1) Right to Access — request copies of your PHI within 30 days; (2) Right to Amendment — request corrections to your PHI; (3) Right to an Accounting of Disclosures — request a list of certain disclosures made of your PHI; (4) Right to Request Restrictions — request limitations on how your PHI is used or disclosed; (5) Right to Confidential Communications — request that we communicate with you by alternative means or at alternative locations; (6) Right to a Paper Copy — obtain a paper copy of this notice upon request; (7) Right to Breach Notification — be notified in the event of a breach of your unsecured PHI as required by the HITECH Act.

MINIMUM NECESSARY STANDARD: The Practice applies the minimum necessary standard when using or disclosing PHI, ensuring that only the minimum amount of information necessary to accomplish the intended purpose is used or disclosed.

DATA SECURITY: The Practice implements administrative, physical, and technical safeguards to protect your PHI, including encryption of electronic records, secure storage of physical records, access controls, and regular security assessments. Electronic health records are maintained using HIPAA-compliant systems.

RETENTION: Medical records are retained for a minimum of 6 years per New York State requirements (10 NYCRR Section 415.5), or longer if required by applicable federal regulations.

COMPLAINTS: If you believe your privacy rights have been violated, you may file a complaint with the Practice's Privacy Officer or with the Secretary of the U.S. Department of Health and Human Services. You will not be retaliated against for filing a complaint.

ELECTRONIC COMMUNICATIONS: The Practice may communicate with you by email, text message (SMS), telehealth platforms, and other electronic means for treatment, scheduling, care coordination, and billing purposes. Standard email and SMS are not fully secure methods of communication and carry a risk that information could be intercepted or accessed by unauthorized persons. By providing your email address or mobile number and electing to receive electronic communications, you acknowledge and accept this risk. You have the right to request confidential communications by alternative means or at an alternative location, and you may withdraw your election to receive electronic communications at any time by notifying the Practice in writing. Telehealth services are delivered using HIPAA-compliant, encrypted platforms.

CHANGES TO THIS NOTICE: The Practice reserves the right to change this notice and to make the revised notice effective for PHI already maintained as well as for PHI received in the future.

ACKNOWLEDGMENT: By signing below, I acknowledge that I have received, read, and understand this Notice of Privacy Practices. I understand my rights regarding my Protected Health Information and how it may be used and disclosed by the Practice.`;

export const CONSENT_MEDICAL = `MEDICAL HISTORY & RELEASE AUTHORIZATION - BT RPN PLLC & Kristina Castro, Nurse Practitioner in Family Health, PLLC, providing services under the licensed name Healing Soulutions
Effective Date: August 1, 2026

I hereby authorize the Practice to: (a) collect, review, and maintain my complete medical history and health information; (b) request and obtain medical records from prior and current healthcare providers, hospitals, laboratories, pharmacies, and other healthcare entities; (c) disclose my medical information to treating providers, consulting specialists, laboratories, pharmacies, and other healthcare professionals involved in my care; (d) use my medical information for treatment, payment, and healthcare operations as described in the Notice of Privacy Practices; and (e) order, obtain, and review laboratory testing and clinical monitoring reasonably necessary to safely provide prescription therapies, including medically supervised weight management and other prescription therapies.

SPECIAL CATEGORIES REQUIRING SEPARATE AUTHORIZATION: I understand that separate written authorization is required for the release of: HIV/AIDS-related information (NY PHL Article 27-F); mental health records (NY MHL Section 33.13); alcohol and substance abuse treatment records (42 CFR Part 2); psychotherapy notes; and genetic information (GINA). These categories of information will not be released without my specific written authorization except as required by law.

OBLIGATION TO DISCLOSE: I understand that I have an affirmative obligation to fully and truthfully disclose all relevant medical information to my clinician, including but not limited to: all current and past medical conditions and diagnoses; all current medications (prescription, over-the-counter, supplements, and herbal remedies) and dosages; all known allergies and prior adverse reactions to medications or substances; all prior surgeries, hospitalizations, and medical procedures; family medical history relevant to my treatment; current pregnancy or plans for pregnancy; and any other information that may be relevant to my care and treatment. I understand that incomplete or inaccurate disclosure may result in serious adverse health consequences, including dangerous drug interactions, allergic reactions, or other complications, and that the Practice shall not be held liable for any adverse outcomes resulting from my failure to provide complete and accurate medical information.

SUBSTANCE USE & PATIENT SAFETY DISCLOSURE: I understand that honestly disclosing the use of all substances—including alcohol, marijuana/cannabis, nicotine, and recreational or illicit drugs—is vital for my safety. Many substances can cause dangerous, life-threatening interactions with the medical treatments, IV therapies, and medications provided by the Practice (e.g., cardiac arrest, seizure, or respiratory failure). Confidentiality: I understand that this information is Protected Health Information (PHI) and will remain confidential in accordance with HIPAA; the Practice does not report substance use to law enforcement. Liability Release: I acknowledge that if I fail to disclose substance use, the Practice cannot anticipate potential drug interactions. Therefore, I agree to hold the Practice and its providers harmless from any adverse reactions or complications that result from my failure to provide a complete and accurate history of substance use.

ACCURACY CERTIFICATION: I certify that all medical information provided by me, whether written or verbal, is complete, accurate, and truthful to the best of my knowledge. I understand that providing false or misleading medical information may constitute fraud and may result in adverse medical outcomes for which the Practice shall bear no liability.

DURATION AND REVOCATION: This authorization shall remain in effect for the duration of my patient relationship with the Practice and for a period of 6 years following the termination of such relationship, in accordance with New York State record retention requirements. I may revoke this authorization in writing at any time, with the understanding that revocation shall not affect any actions already taken in reliance upon this authorization and that revocation may limit the Practice's ability to provide safe and appropriate care.

ACKNOWLEDGMENT: By signing below, I certify that I am at least 18 years of age (or the legal guardian of the patient), that I have read and fully understand this Medical History and Release Authorization, and that I voluntarily authorize the uses and disclosures described herein.`;

export const CONSENT_FINANCIAL = `FINANCIAL AGREEMENT - BT RPN PLLC & Kristina Castro, Nurse Practitioner in Family Health, PLLC, providing services under the licensed name Healing Soulutions
Effective Date: August 1, 2026

PAYMENT TERMS: Payment is due in full at the time of service unless other arrangements have been made in writing in advance. The Practice accepts major credit cards, debit cards, and other approved payment methods. A detailed invoice will be provided upon request.

GOOD FAITH ESTIMATE: Pursuant to the No Surprises Act (Public Law 116-260), you have the right to receive a Good Faith Estimate explaining the expected cost of your medical care. You may request a Good Faith Estimate before scheduling a service. If you receive a bill that is at least $400 more than your Good Faith Estimate, you may dispute the bill. For questions or more information about your right to a Good Faith Estimate, visit www.cms.gov/nosurprises or call 1-800-985-3059.

INSURANCE: The Practice is an out-of-network provider. The patient is solely responsible for all deductibles, copayments, coinsurance, and any services not covered by their insurance plan. The Practice does not guarantee insurance reimbursement and is not responsible for claim denials, underpayments, or disputes with insurance carriers. The patient is responsible for understanding their insurance benefits and coverage prior to receiving services.

CREDIT CARD ON FILE & PAYMENT AUTHORIZATION: I authorize BT RPN PLLC and Kristina Castro, Nurse Practitioner in Family Health, PLLC to securely store my payment card information using PCI-compliant processing. I explicitly authorize the Practice to charge this card for: (1) Time of Service: All copays, deductibles, or service fees due on the date of care. (2) Late Cancellations/No-Shows: Fees associated with failing to cancel within 24 hours, as per the Cancellation Policy. (3) Outstanding Balances: Any remaining balance after insurance adjudication (if applicable). The Practice agrees to notify me via email or text message at least 48 hours prior to charging my card for any post-service outstanding balance exceeding $50.00. CARD VERIFICATION: To confirm my payment card at the time of booking, I authorize a small, temporary verification hold. This hold is applied solely to verify the card, is not a charge for services, and is released automatically.

PRICING AND FEES: Service pricing is subject to change with 30 days advance notice. Prescription medications, compounded medications, injectable therapies, specialty supplies, and additional materials may incur separate charges beyond the base service fee. Travel fees may apply for locations outside the standard service area. Emergency or after-hours service requests may be subject to additional surcharges.

CANCELLATION AND NO-SHOW POLICY: A minimum of 24 hours advance notice is required for appointment cancellations or rescheduling. Cancellations made less than 24 hours before the scheduled appointment are subject to a late cancellation fee of up to the full cost of the scheduled service. Failure to be present and available at the scheduled appointment time (no-show) is subject to a fee of up to the full cost of the scheduled service. Repeated late cancellations or no-shows (three or more within a 12-month period) may result in a required prepayment for future appointments or termination of the patient relationship.

PAST DUE ACCOUNTS AND COLLECTIONS: Balances remaining unpaid for 60 or more days may be referred to a third-party collections agency. In the event of collections action, the patient shall be responsible for all collection costs, including but not limited to collection agency fees, court costs, and reasonable attorneys' fees. Past due accounts may accrue interest at the maximum rate permitted by New York State law. The Practice reserves the right to decline future services until all outstanding balances are paid in full.

DISPUTE RESOLUTION: Any billing disputes must be submitted in writing within 30 days of the date of the invoice. The Practice will review all disputes in good faith and respond within 15 business days. Unresolved disputes shall be subject to the dispute resolution provisions set forth in the Informed Consent for Treatment.

TELEPHONE & TEXT MESSAGE (SMS) COMMUNICATIONS CONSENT: I expressly consent to receive telephone calls and text messages from the Practice at the telephone number(s) I provide, including calls or texts made using an automatic telephone dialing system or an artificial or prerecorded voice, for non-marketing purposes such as appointment scheduling and reminders, care coordination, billing, and payment matters, consistent with the Telephone Consumer Protection Act (TCPA, 47 U.S.C. Section 227). Message and data rates may apply and message frequency may vary. I may opt out of text messages at any time by replying STOP, and may opt out of non-emergency calls by notifying the Practice. Consent to receive marketing or promotional communications is not a condition of receiving services. I understand that opting out of certain communications may affect the Practice's ability to send reminders or account notices.

ACKNOWLEDGMENT: By signing below, I certify that I am at least 18 years of age (or the legal guardian of the patient), that I have read and fully understand this Financial Agreement, that I accept financial responsibility for all services rendered, and that I agree to all terms and conditions set forth herein.`;

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   ICONS
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
